<select name="dep"><?php if($dregion){ echo '<option ="' . $dregion . '">' . $dregion . '</option>'; } ?>
	<option value='01 - Ain'>01 - Ain</option>
	<option value='02 - Aisne'>02 - Aisne</option>
	<option value='03 - Allier'>03 - Allier</option>
	<option value='04 - Alpes de Haute Provence'>04 - Alpes de Haute Provence</option>
	<option value='05 - Alpes (Hautes)'>05 - Alpes (Hautes)</option>
	<option value='06 - Alpes Maritimes'>06 - Alpes Maritimes</option>
	<option value='07 - Ardèche'>07 - Ard&egrave;che</option>
	<option value='08 - Ardennes'>08 - Ardennes</option>
	<option value='09 - Ariège'>09 - Ari&egrave;ge</option>
	<option value='10 - Aube'>10 - Aube</option>
	<option value='11 - Aude'>11 - Aude</option>
	<option value='12 - Aveyron'>12 - Aveyron</option>
	<option value='13 - Bouches du Rhône'>13 - Bouches du Rh&ocirc;ne</option>
	<option value='14 - Calvados'>14 - Calvados</option>
	<option value='15 - Cantal'>15 - Cantal</option>
	<option value='16 - Charente'>16 - Charente</option>
	<option value='17 - Charente Maritime'>17 - Charente Maritime</option>
	<option value='18 - Cher'>18 - Cher</option>
	<option value='19 - Corrèze'>19 - Corrèze</option>
	<option value='20 - Corse'>20 - Corse</option>
	<option value="21 - Côte d'Or">21 - C&ocirc;te d&acute;Or</option>
	<option value="22 - Côtes d'Armor">22 - C&ocirc;tes d&acute;Armor</option>
	<option value='23 - Creuse'>23 - Creuse</option>
	<option value='24 - Dordogne'>24 - Dordogne</option>
	<option value='25 - Doubs'>25 - Doubs</option>
	<option value='26 - Drôme'>26 - Dr&ocirc;me</option>
	<option value='27 - Eure'>27 - Eure</option>
	<option value='28 - Eure et Loir'>28 - Eure et Loir</option>
	<option value='29 - Finistère'>29 - Finist&egrave;re</option>
	<option value='30 - Gard'>30 - Gard</option>
	<option value='31 - Garonne (Haute)'>31 - Garonne (Haute)</option>
	<option value='32 - Gers'>32 - Gers</option>
	<option value='33 - Gironde'>33 - Gironde</option>
	<option value="34 - Hérault">34 - H&eacute;rault</option>
	<option value='35'>35 - Ille et Vilaine</option>
	<option value='36'>36 - Indre</option>
	<option value='37'>37 - Indre et Loire</option>
	<option value='38 - Isère'>38 - Is&egrave;re</option>
	<option value='39 - Jura'>39 - Jura</option>
	<option value='40 - Landes'>40 - Landes</option>
	<option value='41 - Loir et Cher'>41 - Loir et Cher</option>
	<option value='42 - Loire'>42 - Loire</option>
	<option value='43 - Loire (Haute)'>43 - Loire (Haute)</option>
	<option value='44 - Loire Atlantique'>44 - Loire Atlantique</option>
	<option value='45 - Loire'>45 - Loiret</option>
	<option value='46 - Lot'>46 - Lot</option>
	<option value='47 - Lot et Garonne'>47 - Lot et Garonne</option>
	<option value='48 - Lozére'>48 - Loz&egrave;re</option>
	<option value='49 - Maine et Loire'>49 - Maine et Loire</option>
	<option value='50 - Manche'>50 - Manche</option>
	<option value='51 - Marne'>51 - Marne</option>
	<option value='52 - Marne (Haute)'>52 - Marne (Haute)</option>
	<option value='53 - Mayenne'>53 - Mayenne</option>
	<option value='54 - Meurthe et Moselle'>54 - Meurthe et Moselle</option>
	<option value='55 - Meuse'>55 - Meuse</option>
	<option value='56 - Morbihan'>56 - Morbihan</option>
	<option value='57 - Moselle'>57 - Moselle</option>
	<option value='58 - Niévre'>58 - Ni&egrave;vre</option>
	<option value='59 - Nord'>59 - Nord</option>
	<option value='60 - Oise'>60 - Oise</option>
	<option value='61 - Orne'>61 - Orne</option>
	<option value='62 - Pas de Calais'>62 - Pas de Calais</option>
	<option value='63 - Puy de Dôme'>63 - Puy de D&ocirc;me</option>
	<option value='64 - Pyrénées Atlantiques'>64 - Pyr&eacute;n&eacute;es Atlantiques</option>
	<option value='65 - Pyrénées (Hautes)'>65 - Pyr&eacute;n&eacute;es (Hautes)</option>
	<option value='66 - Pyrénées Orientales'>66 - Pyr&eacute;n&eacute;es Orientales</option>
	<option value='67 - Rhin (Bas)'>67 - Rhin (Bas)</option>
	<option value='68 - Rhin (Haut)'>68 - Rhin (Haut)</option>
	<option value='69 - Rhône'>69 - Rh&ocirc;ne</option>
	<option value='70 - Saône (Haute'>70 - Sa&ocirc;ne (Haute)</option>
	<option value='71 - Saône et Loire'>71 - Sa&ocirc;ne et Loire</option>
	<option value='72 - Sarthe'>72 - Sarthe</option>
	<option value='73 - Savoie'>73 - Savoie</option>
	<option value='74 - Savoie (Haute)'>74 - Savoie (Haute)</option>
	<option value='75 - Paris (Dept.)'>75 - Paris (Dept.)</option>
	<option value='76 - Seine Maritime'>76 - Seine Maritime</option>
	<option value='77 - Seine et Marne'>77 - Seine et Marne</option>
	<option value='78 - Yvelines'>78 - Yvelines</option>
	<option value='79 - Sèvres (Deux)'>79 - S&egrave;vres (Deux)</option>
	<option value='80 - Somme'>80 - Somme</option>
	<option value='81 - Tarn'>81 - Tarn</option>
	<option value='82 - Tarn et Garonne'>82 - Tarn et Garonne</option>
	<option value='83 - Var'>83 - Var</option>
	<option value='84 - Vaucluse'>84 - Vaucluse</option>
	<option value='85 - Vendée'>85 - Vend&eacute;e</option>
	<option value='86 - Vienne'>86 - Vienne</option>
	<option value='87 - Vienne (Haute)'>87 - Vienne (Haute)</option>
	<option value='88 - Vosges'>88 - Vosges</option>
	<option value='89 - Yonne'>89 - Yonne</option>
	<option value='90 - Belfort (Territoire de)'>90 - Belfort (Territoire de)</option>
	<option value='91 - Essonn'>91 - Essonne</option>
	<option value='92 - Hauts de Seine'>92 - Hauts de Seine</option>
	<option value='93 - Seine Saint Denis'>93 - Seine Saint Denis</option>
	<option value='94 - Val de Marne'>94 - Val de Marne</option>
	<option value="95 - Val d'Oise">95 - Val d&acute;Oise</option>
</select>